# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be4f85a4ceb56e0bfdd17bb85c386da8c40e29f5bcad8897b14a4276a23c364e5194e831128be236836cffbde79333d90234c786a8a8e182367fdf3042f6e0e9

test:
  secret_key_base: 3195b0b8fa5ec2daec17260cc5a610fc26e765fe3b874b873081fcec487b6da8611aca45398c3f3a45baf871f7df32db411de0bc6983e904a1fa2891e9d71c32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
